### ISSUE TITLE
about VAP_extract.py

### ISSUE THREAD

**Issue by Dingkx9** [HeZhang1994/video-audio-processing#1]
when u extract audio from a video ,u need a folder to store the audio,I see ur code remove the out_file.I'm so confused and can't figure it out

**Comment by HeZhang1994** [comment]
> when u extract audio from a video ,u need a folder to store the audio,I see ur code remove the out_file.I'm so confused and can't figure it out

**Comment by HeZhang1994** [comment]
Hi, 

```os.remove(out_file)``` only removes the file in the folder. It will not delete the parent folder.

The reason to remove the ```out_file``` (if exists) is that the given ffmpeg command cannot overwrite to the existing output file (i.e., failed to extract the audio). I just want to make sure this code run properly in repeated times.

Regards,
He

**Comment by Dingkx9** [comment]
ok，I got u,Thanks.But,I didn't acquire a .mp3 file when I run this code.No error but no .mp3 file either.If the dependency need Ubuntu? Cuz I use Windows.

**Comment by HeZhang1994** [comment]
Hi, I have tested this code on Ubuntu and Mac OS. :P

If the path of the input video is correct, could you please check if the "ffmpeg" library is correctly installed on your Windows OS? 

To install "ffmpeg" on Windows OS, see this link: https://github.com/adaptlearning/adapt_authoring/wiki/Installing-FFmpeg

Good luck!
He

**Comment by HeZhang1994** [comment]
Hi, I have modified the code by replacing the "Path" in "pathlib" library with "os.path" in "os".

Regards,
He

**Comment by Dingkx9** [comment]
Ur modification is great.Last time I just install ffmpeg module in the python.Now I'm sure I install it correctly.But I still fali to acquire a .mp3 file.So I directly run the command on cmd.exe,it tells me no such a file or directory,I'm sure there it is. I'm gonna figure it out.Thanks a lot,much appreciation

**Comment by HeZhang1994** [comment]
Hi, maybe you should check the "format" of input path? For example, the format of the path is different in Windows and Ubuntu (/ or \ or //).

Regards,
He

**Comment by Dingkx9** [comment]
I guess that's not the point.My partner used Ubuntu to run this code and he succeed.Maybe it's Incompatibility of Windows or something is wrong with my computer.

**Comment by HeZhang1994** [comment]
OK, I hope you can figure it out or just Ubuntu with VM.

**Comment by HeZhang1994** [comment]
If you have any further questions, please reopen this issue. Good luck! :-)

**Comment by HeZhang1994** [comment]
Hi Dingkx9,

I just found the difference of ffmpeg version I have tested on MacOS and Linux. Maybe you could check the version of ffmpeg you have installed. I would suggest you to use the lasted version (4.1). I will update the README with how to install/upgrade ffmpeg on Linux.

He

**Comment by Dingkx9** [comment]
All right.I have install a ubuntu system .And ur code works well
