### ISSUE TITLE
Functionality Request: Take commandline argument and automatic compression

### ISSUE THREAD

**Issue by ZhangTianrong** [HeZhang1994/video-audio-processing#2]
I think you can probably just include argparse and add 2 positional argument, one required for the input file and one optional for the output with default value the same as the input except for the extension name.

**Comment by ZhangTianrong** [comment]
Em…… I also notice a problem with the audio extraction. My input mp4 is roughly 60MB while the output wav is over 350MB. I tried to compress it into flac but the flac version is still as large as nearly 100MB. I don't know much about ffmpeg  but I wonder if it is possible to select the compression method according to the quality of the input file since it makes no sense to ask for an uncompressed audio out of a random video.

**Comment by HeZhang1994** [comment]
> Em…… I also notice a problem with the audio extraction. My input mp4 is roughly 60MB while the output wav is over 350MB. I tried to compress it into flac but the flac version is still as large as nearly 100MB. I don't know much about ffmpeg but I wonder if it is possible to select the compression method according to the quality of the input file since it makes no sense to ask for an uncompressed audio out of a random video.

Hi Tianrong, I would like to suggest you set the output audio format as 'output.mp3' instead of 'output.wav' in the Python code. '.mp3' is a compressed audio format that will let you have a small audio file.

**Comment by HeZhang1994** [comment]
> I think you can probably just include argparse and add 2 positional argument, one required for the input file and one optional for the output with default value the same as the input except for the extension name.

Hi Tianrong, This is a really good suggestion. I include everything in the Python code/script because this might be easier for checking and further development (e.g., video/audio editing requires multiple FFmpeg commands).

If you would like to extract audio in the Terminal, you can simply use the following command in the Terminal
`ffmpeg -i INPUT_VIDEO.mp4 -ab 160k -ac 2 -ar 44100 -vn OUTPUT_FILE.mp3`.

**Comment by ZhangTianrong** [comment]
> > Em…… I also notice a problem with the audio extraction. My input mp4 is roughly 60MB while the output wav is over 350MB. I tried to compress it into flac but the flac version is still as large as nearly 100MB. I don't know much about ffmpeg but I wonder if it is possible to select the compression method according to the quality of the input file since it makes no sense to ask for an uncompressed audio out of a random video.
> 
> Hi Tianrong, I would like to suggest you set the output audio format as 'output.mp3' instead of 'output.wav' in the Python code. '.mp3' is a compressed audio format that will let you have a small audio file.

Thanks  for that. However, I just find out the `-acodec copy` option which seem to be able to preserve the original format. For example in my case it is `Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 190 kb/s`. You could possibly include that in your code.

**Comment by HeZhang1994** [comment]
> > > Em…… I also notice a problem with the audio extraction. My input mp4 is roughly 60MB while the output wav is over 350MB. I tried to compress it into flac but the flac version is still as large as nearly 100MB. I don't know much about ffmpeg but I wonder if it is possible to select the compression method according to the quality of the input file since it makes no sense to ask for an uncompressed audio out of a random video.
> > 
> > 
> > Hi Tianrong, I would like to suggest you set the output audio format as 'output.mp3' instead of 'output.wav' in the Python code. '.mp3' is a compressed audio format that will let you have a small audio file.
> 
> Thanks for that. However, I just find out the `-acodec copy` option which seem to be able to preserve the original format. For example in my case it is `Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 190 kb/s`. You could possibly include that in your code.

Hi, it is a really good idea to add `-acodec copy` into the command, which will preserve the quality of the original audio/video. However, in the case of processing video, this command will lead to a short period of black frames at the beginning of the output video.

Cheers!
